### ISSUE TITLE
Importing jskos-validate is slow

### ISSUE THREAD

**Issue by nichtich** [gbv/jskos-validate#15]
Adding `import validate from "jskos-validate"` to your code will introduce a delay of half a second (depending on machine), can this be speed up? I guess it's the for-loop in `lib/validate.js` to sequentially compile JSON Schemas with ajv. Doing it in parallel with promises requires to switch jskos-validate to ES-modules.

**Comment by nichtich** [comment]
We could generate pre-compile schemas and distribute as [standalone validation code](https://github.com/ajv-validator/ajv/blob/master/docs/standalone.md).

**Comment by stefandesu** [comment]
Yes, we should do that! Didn't realize it was an option. It will require a build step though that we don't currently have. Ideally, I would like to use the same system that we're using in cocoda-sdk and login-client (esbuild), but that would indeed require a rewrite to ES modules syntax.

How urgent is this? Is there a particular project where you noticed the slow startup due to jskos-validate?
